In [1]:
import pandas as pd

In [57]:
datafr=pd.read_excel("E:/tugas_koko/Mencari_Kerja/Kerjaan/Data/bencana_dan_wilayah_24032023_231519.xlsx")

In [58]:
datafr

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,Statistik Bencana Menurut Wilayah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Tanah Longsor, Indonesia, 2023",NaN,NaN,NaN,NaN
2,NaN,Wilayah,Jumlah,Korban,NaN,NaN,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
4,NaN,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16)
5,NaN,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,NaN,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
7,NaN,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
8,NaN,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
9,NaN,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,NaN,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
11,NaN,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
12,NaN,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,NaN,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
14,NaN,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0
15,NaN,Bidang Pengelolaan Data dan Sistem Informasi (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Pusat Data Informasi dan Komunikasi Kebencanaa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Badan Nasional Penanggulangan Bencana (BNPB),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
datafr.drop("Unnamed: 0", axis=1, inplace=True)

In [60]:
datafr.columns = datafr.iloc[3]

In [61]:
datafr

3,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
0,Statistik Bencana Menurut Wilayah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Tanah Longsor, Indonesia, 2023",NaN,NaN,NaN,NaN
2,Wilayah,Jumlah,Korban,NaN,NaN,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16)
5,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
7,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
8,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
9,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
11,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
12,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
14,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0
15,Bidang Pengelolaan Data dan Sistem Informasi (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Pusat Data Informasi dan Komunikasi Kebencanaa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Badan Nasional Penanggulangan Bencana (BNPB),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
datafr = datafr.drop([0,1,2,3,4], axis=0)
datafr

3,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
5,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
7,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
8,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
9,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
11,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
12,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
14,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0
15,Bidang Pengelolaan Data dan Sistem Informasi (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Pusat Data Informasi dan Komunikasi Kebencanaa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Badan Nasional Penanggulangan Bencana (BNPB),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
datafr = datafr.reset_index(drop=True)

In [64]:
# change column names
datafr.columns = ['Wilayah', 'Jumlah', 'Meninggal', 'Hilang', 'Terluka', 'Menderita', 'Mengungsi', 'Rumah', 'Pendidikan', 'Kesehatan', 'Peribadatan', 'Fasum', 'Perkantoran', 'Jembatan', 'Pabrik', 'Kios']
datafr

,Wilayah,Jumlah,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
0,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
2,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
3,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
4,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
6,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
7,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
9,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0
10,Bidang Pengelolaan Data dan Sistem Informasi (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Pusat Data Informasi dan Komunikasi Kebencanaa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Badan Nasional Penanggulangan Bencana (BNPB),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
#Drop column yang ada di row terakhir
to_drop = ["Bidang Pengelolaan Data dan Sistem Informasi (PDSI),",
           "Pusat Data Informasi dan Komunikasi Kebencanaan (Pusdatinkom),",
           "Badan Nasional Penanggulangan Bencana (BNPB)",
           "Jumlah"]
datafr = datafr[~datafr.iloc[:,0].isin(to_drop)]
datafr

,Wilayah,Jumlah,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
0,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
2,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
3,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
4,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
6,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
7,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0

In [14]:
datafr.to_csv("E:/tugas_koko/Mencari_Kerja/Kerjaan/Data/bencana_dan_wilayah_24032023_231519.csv")

In [10]:
datafr = datafr.drop(datafr[datafr['Unnamed: 1'].isna() | (datafr['Unnamed: 1'] == 'Bidang Pengelolaan Data dan Sistem Informasi')].index)

In [11]:
datafr

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,Statistik Bencana Menurut Wilayah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Wilayah,Jumlah,Korban,NaN,NaN,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16)
5,NaN,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,NaN,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
7,NaN,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
8,NaN,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
9,NaN,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,NaN,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
11,NaN,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
12,NaN,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,NaN,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
14,NaN,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0
15,NaN,Bidang Pengelolaan Data dan Sistem Informasi (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Pusat Data Informasi dan Komunikasi Kebencanaa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Badan Nasional Penanggulangan Bencana (BNPB),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Merge row 2 and 3
datafr = pd.concat([datafr.iloc[2], datafr.iloc[3]], axis=1).T

# Reset the index
datafr = datafr.reset_index(drop=True)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,Wilayah,Jumlah,Korban,NaN,NaN,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios

In [7]:
datafr

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,Wilayah,Jumlah,Korban,NaN,NaN,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios

In [55]:
# Drop column "Unnamed: 0"
datafr.drop(1, axis=1, inplace=True)

KeyError: '[1] not found in axis'

In [56]:
datafr

3,NaN,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
5,NaN,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,NaN,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
7,NaN,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
8,NaN,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
9,NaN,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,NaN,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
11,NaN,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
12,NaN,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,NaN,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
14,NaN,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0
15,NaN,Bidang Pengelolaan Data dan Sistem Informasi (...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,Pusat Data Informasi dan Komunikasi Kebencanaa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,Badan Nasional Penanggulangan Bencana (BNPB),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
to_drop = ["Bidang Pengelolaan Data dan Sistem Informasi (PDSI),",
           "Pusat Data Informasi dan Komunikasi Kebencanaan (Pusdatinkom),",
           "Badan Nasional Penanggulangan Bencana (BNPB)"]
datafr = datafr[~datafr.iloc[:,0].isin(to_drop)]

In [20]:
datafr

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Statistik Bencana Menurut Wilayah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Tanah Longsor, Indonesia, 2023",NaN,NaN,NaN,NaN
2,Wilayah,Jumlah,Korban,NaN,NaN,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
4,(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16)
5,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
7,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
8,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
9,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
11,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
12,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
14,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0

In [22]:
datafr = datafr.drop(1, axis=0)
datafr

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Statistik Bencana Menurut Wilayah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Wilayah,Jumlah,Korban,NaN,NaN,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
5,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
7,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
8,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
9,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
11,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
12,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
14,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0

In [24]:
df_prepros = datafr.drop(0) # drop rows
# df_prepros = df_prepros.drop(columns=['Unnamed: 0']) # drop column
df_prepros = df_prepros.set_index(['Unnamed: 2', 'Unnamed: 3']) # set multi-level index
df_prepros.index.names = ['Wilayah', 'Jumlah'] # set index names

In [25]:
df_prepros

                                Unnamed: 1 Unnamed: 4 Unnamed: 5 Unnamed: 6  \
Wilayah Jumlah
Jumlah  Korban                     Wilayah        NaN        NaN        NaN
NaN     Meninggal                      NaN     Hilang    Terluka  Menderita
1       0               12. Sumatera Utara          0          0          0
3       0             16. Sumatera Selatan          0          0          5
1       0                      18. Lampung          0          0          0
        46              21. Kepulauan Riau          8          4          0
6       0                   32. Jawa Barat          0          0          0
37      0                  33. Jawa Tengah          0          0          0
22      0                   35. Jawa Timur          0          1          0
1       0          53. Nusa Tenggara Timur          0          0          0
4       0             61. Kalimantan Barat          0          0          0
76      46                          Jumlah          8          5          5

                  Unnamed: 7 Unnamed: 8  Unnamed: 9 Unnamed: 10  Unnamed: 11  \
Wilayah Jumlah
Jumlah  Korban           NaN  Kerusakan         NaN         NaN          NaN
NaN     Meninggal  Mengungsi      Rumah  Pendidikan   Kesehatan  Peribadatan
1       0                  0          0           0           0            0
3       0                  1          5           0           0            0
1       0                  0          4           0           0            0
        46              2240         30           0           0            0
6       0                  0          0           0           0            0
37      0                  0         17           0           0            1
22      0                  0         15           0           0            0
1       0                  0          0           0           0            0
4       0                  0         13           0           0            0
76      46              2241         84           0           0            1

                  Unnamed: 12  Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16
Wilayah Jumlah
Jumlah  Korban            NaN          NaN         NaN         NaN         NaN
NaN     Meninggal       Fasum  Perkantoran    Jembatan      Pabrik        Kios
1       0                   0            0           0           0           0
3       0                   0            0           0           0           0
1       0                   0            0           0           0           0
        46                  0            0           0           0           0
6       0                   0            0           0           0           0
37      0                   1            0           1           0           0
22      0                   0            0           1           0           0
1       0                   0            0           0           0           0
4       0                   0            0           0           0           0
76      46                  1            0           2           0           0

In [26]:
datafr.columns = datafr.iloc[2]

In [27]:
datafr

3,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
0,Statistik Bencana Menurut Wilayah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Wilayah,Jumlah,Korban,NaN,NaN,NaN,NaN,Kerusakan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
5,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
7,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
8,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
9,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
11,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
12,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
14,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0

In [29]:
datafr = datafr.drop([0,2,3])

In [30]:
datafr

3,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
5,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
7,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
8,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
9,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
11,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
12,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
14,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0

In [31]:
datafr = datafr.reset_index(drop=True)

In [32]:
datafr

3,NaN,NaN,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
0,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
2,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
3,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
4,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
6,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
7,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
9,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0

In [33]:
datafr.to_csv("E:/tugas_koko/Mencari_Kerja/Kerjaan/Data/bencana_dan_wilayah_24032023_231519.csv")

In [36]:
# change column names
datafr.columns = ['Wilayah', 'Jumlah', 'Meninggal', 'Hilang', 'Terluka', 'Menderita', 'Mengungsi', 'Rumah', 'Pendidikan', 'Kesehatan', 'Peribadatan', 'Fasum', 'Perkantoran', 'Jembatan', 'Pabrik', 'Kios']

# change index names
datafr = datafr.rename(index={0: '', 1: 'Wilayah', 2: 'Jumlah'})

# reset index
datafr = datafr.reset_index(drop=True)

In [37]:
datafr

,Wilayah,Jumlah,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
0,12. Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,16. Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
2,18. Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
3,21. Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
4,32. Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,33. Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
6,35. Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
7,53. Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,61. Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
9,Jumlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0

In [38]:
datafr['Wilayah'] = datafr['Wilayah'].apply(lambda x: x[x.find('. ')+2:])

In [39]:
datafr

,Wilayah,Jumlah,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
0,Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
2,Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
3,Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
4,Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
6,Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
7,Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0
9,umlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0

In [40]:
datafr.drop(9)

,Wilayah,Jumlah,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios
0,Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0
2,Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0
3,Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0
4,Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0
6,Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0
7,Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0

In [41]:
datafr['Jenis Bencana'] = 'Tanah Longsor'
datafr['Tahun'] = 2023

In [42]:
datafr

,Wilayah,Jumlah,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios,Jenis Bencana,Tahun
0,Sumatera Utara,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Tanah Longsor,2023
1,Sumatera Selatan,3,0,0,0,5,1,5,0,0,0,0,0,0,0,0,Tanah Longsor,2023
2,Lampung,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0,Tanah Longsor,2023
3,Kepulauan Riau,1,46,8,4,0,2240,30,0,0,0,0,0,0,0,0,Tanah Longsor,2023
4,Jawa Barat,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Tanah Longsor,2023
5,Jawa Tengah,37,0,0,0,0,0,17,0,0,1,1,0,1,0,0,Tanah Longsor,2023
6,Jawa Timur,22,0,0,1,0,0,15,0,0,0,0,0,1,0,0,Tanah Longsor,2023
7,Nusa Tenggara Timur,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Tanah Longsor,2023
8,Kalimantan Barat,4,0,0,0,0,0,13,0,0,0,0,0,0,0,0,Tanah Longsor,2023
9,umlah,76,46,8,5,5,2241,84,0,0,1,1,0,2,0,0,Tanah Longsor,2023

In [46]:
datafr.to_csv("E:/tugas_koko/Mencari_Kerja/Kerjaan/Data/df_TanahLongsor_2023.csv")

In [71]:
file_path = "E:/tugas_koko/Mencari_Kerja/Kerjaan/Data/Puting Beliung_2022.xlsx"

In [72]:
import os

In [73]:
file_name = os.path.splitext(os.path.basename(file_path))[0]

In [74]:
year = file_name.split('_')[1]

In [76]:
disaster = file_name.split('_')[0]

disaster

In [75]:
year

'2022'

In [1]:
from Preprocess import processing_data

In [3]:
path_file= "E:/tugas_koko/Mencari_Kerja/Kerjaan/Data/Puting Beliung_2022.xlsx"

In [4]:
datafr =processing_data(path_file)

In [5]:
datafr

,Wilayah,Jumlah,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios,Jenis Bencana,Tahun
0,Aceh,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Puting Beliung,2022
1,Sumatera Utara,19,0,0,0,3652,0,803,0,0,0,8,0,0,0,0,Puting Beliung,2022
2,Sumatera Barat,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Puting Beliung,2022
3,Sumatera Selatan,63,0,0,11,171,84,669,2,2,1,7,15,0,0,2,Puting Beliung,2022
4,Lampung,3,0,0,0,100,0,28,0,0,0,0,0,0,0,0,Puting Beliung,2022
5,Bangka Belitung,24,0,0,0,52,183,174,1,0,1,0,1,0,0,0,Puting Beliung,2022
6,Kepulauan Riau,1,0,0,0,0,0,3,0,0,0,0,0,0,0,0,Puting Beliung,2022
7,Jawa Barat,88,0,0,1,263,4,542,0,0,0,5,0,0,0,7,Puting Beliung,2022
8,Jawa Tengah,316,1,0,10,33,31,1267,16,3,11,29,1,1,6,17,Puting Beliung,2022
9,Jawa Timur,78,0,0,6,0,11,231,4,0,2,1,2,0,2,16,Puting Beliung,2022
10,Nusa Tenggara Barat,1,0,0,0,0,10,10,0,0,0,0,0,0,0,0,Puting Beliung,2022
11,Kalimantan Selatan,1,0,0,0,27,0,1,0,0,0,0,0,0,0,0,Puting Beliung,2022
12,Kalimantan Utara,4,0,0,0,0,7,4,0,0,0,0,0,0,0,0,Puting Beliung,2022
13,Sulawesi Utara,8,0,0,0,1,4,8,0,0,0,0,0,0,0,0,Puting Beliung,2022
14,Sulawesi Tengah,7,0,0,0,0,0,5,0,0,3,0,0,0,0,0,Puting Beliung,2022
15,Sulawesi Selatan,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,Puting Beliung,2022
16,Sulawesi Tenggara,3,0,0,0,0,0,16,0,0,0,0,0,0,0,0,Puting Beliung,2022
17,Papua,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0,Puting Beliung,2022

In [6]:
datafr['id'] = datafr[['Wilayah', 'Jenis Bencana','Tahun']].sum(axis=1).map(hash)

In [7]:
datafr

,Wilayah,Jumlah,Meninggal,Hilang,Terluka,Menderita,Mengungsi,Rumah,Pendidikan,Kesehatan,Peribadatan,Fasum,Perkantoran,Jembatan,Pabrik,Kios,Jenis Bencana,Tahun,id
0,Aceh,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Puting Beliung,2022,8543438165990499114
1,Sumatera Utara,19,0,0,0,3652,0,803,0,0,0,8,0,0,0,0,Puting Beliung,2022,-9129522240541270886
2,Sumatera Barat,24,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Puting Beliung,2022,6263507462038765455
3,Sumatera Selatan,63,0,0,11,171,84,669,2,2,1,7,15,0,0,2,Puting Beliung,2022,-5384625073463145789
4,Lampung,3,0,0,0,100,0,28,0,0,0,0,0,0,0,0,Puting Beliung,2022,4032544041898762264
5,Bangka Belitung,24,0,0,0,52,183,174,1,0,1,0,1,0,0,0,Puting Beliung,2022,-4323934236605449301
6,Kepulauan Riau,1,0,0,0,0,0,3,0,0,0,0,0,0,0,0,Puting Beliung,2022,3622251699889910245
7,Jawa Barat,88,0,0,1,263,4,542,0,0,0,5,0,0,0,7,Puting Beliung,2022,-4172647100127863260
8,Jawa Tengah,316,1,0,10,33,31,1267,16,3,11,29,1,1,6,17,Puting Beliung,2022,-6160434174730638774
9,Jawa Timur,78,0,0,6,0,11,231,4,0,2,1,2,0,2,16,Puting Beliung,2022,-7332032656612423542
10,Nusa Tenggara Barat,1,0,0,0,0,10,10,0,0,0,0,0,0,0,0,Puting Beliung,2022,-8063306150661036980
11,Kalimantan Selatan,1,0,0,0,27,0,1,0,0,0,0,0,0,0,0,Puting Beliung,2022,-502916662515351933
12,Kalimantan Utara,4,0,0,0,0,7,4,0,0,0,0,0,0,0,0,Puting Beliung,2022,6170715927579166178
13,Sulawesi Utara,8,0,0,0,1,4,8,0,0,0,0,0,0,0,0,Puting Beliung,2022,-2250775400715298765
14,Sulawesi Tengah,7,0,0,0,0,0,5,0,0,3,0,0,0,0,0,Puting Beliung,2022,6279137909206803322
15,Sulawesi Selatan,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,Puting Beliung,2022,6281138674243225077
16,Sulawesi Tenggara,3,0,0,0,0,0,16,0,0,0,0,0,0,0,0,Puting Beliung,2022,-4305101660199921237
17,Papua,1,0,0,0,0,0,4,0,0,0,0,0,0,0,0,Puting Beliung,2022,5366987442909265699

In [9]:
import os

In [10]:
excel_dir = 'E:/tugas_koko/Mencari_Kerja/Kerjaan/Data'
excel_files = [f for f in os.listdir(excel_dir) if f.endswith('.json')]
print(excel_files)

[]

In [3]:
from Preprocess import processing_data
import os
import pandas as pd

In [3]:
path_file= "E:/tugas_koko/Mencari_Kerja/Kerjaan/Paw_Patrol/Development/Data/Banjir_2021.xlsx"
json_file=processing_data(path_file)

In [3]:
print(json_file)

None

In [6]:
excel_dir = 'E:/tugas_koko/Mencari_Kerja/Kerjaan/Data'
excel_files = [f for f in os.listdir(excel_dir) if f.endswith('.xlsx')]

        # load data from each file into a dictionary and store in a list

In [7]:
data_list = []
for file_name in excel_files:
    with open(os.path.join(excel_dir, file_name), 'r') as f:
        data = processing_data(f)
        data_list.append(data)

TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

In [5]:
data_list

[]

In [15]:
# Directory containing xlsx files
dir_path = "E:/tugas_koko/Mencari_Kerja/Kerjaan/Paw_Patrol/Development/Data"

# List of xlsx file names in the directory
file_names = os.listdir(dir_path)

# Process each file
for file_name in file_names:
    if file_name.endswith(".xlsx"):
        file_path = os.path.join(dir_path, file_name)
        datafr = processing_data(file_path)

In [6]:
import pandas as pd

In [14]:
# create a sample DataFrame
datafr = pd.DataFrame({
    'Wilayah': ['Aceh', 'Bali'],
    'Jumlah': [81, 65],
    'Meninggal': [3, 2],
    'Hilang': [None, None],
    'Terluka': [None, 5],
    'Menderita': [133668, 54321]
})

# convert DataFrame to JSON string
json_str = datafr.to_json(orient='records', indent=4)

# print JSON string
print(json_str)

[
    {
        "Wilayah":"Aceh",
        "Jumlah":81,
        "Meninggal":3,
        "Hilang":null,
        "Terluka":null,
        "Menderita":133668
    },
    {
        "Wilayah":"Bali",
        "Jumlah":65,
        "Meninggal":2,
        "Hilang":null,
        "Terluka":5.0,
        "Menderita":54321
    }
]

In [16]:
datafr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Wilayah    2 non-null      object
 1   Jumlah     2 non-null      int64
 2   Meninggal  2 non-null      int64
 3   Hilang     0 non-null      object
 4   Terluka    1 non-null      float64
 5   Menderita  2 non-null      int64
dtypes: float64(1), int64(3), object(2)
memory usage: 224.0+ bytes

In [24]:
print(json_str)

[
    {
        "Wilayah":"Aceh",
        "Jumlah":81,
        "Meninggal":3,
        "Hilang":null,
        "Terluka":null,
        "Menderita":133668
    },
    {
        "Wilayah":"Bali",
        "Jumlah":65,
        "Meninggal":2,
        "Hilang":null,
        "Terluka":5.0,
        "Menderita":54321
    }
]

In [4]:
path_file= "E:/tugas_koko/Mencari_Kerja/Kerjaan/Paw_Patrol/Development/Data/Banjir_2021.xlsx"
json_file,df_file=processing_data(path_file)

In [5]:
df_file.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33 entries, 0 to 32
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Wilayah        33 non-null     object
 1   Jumlah         33 non-null     int64
 2   Meninggal      33 non-null     int64
 3   Hilang         33 non-null     int64
 4   Terluka        33 non-null     int64
 5   Menderita      33 non-null     int64
 6   Mengungsi      33 non-null     int64
 7   Rumah          33 non-null     int64
 8   Pendidikan     33 non-null     int64
 9   Kesehatan      33 non-null     int64
 10  Peribadatan    33 non-null     int64
 11  Fasum          33 non-null     int64
 12  Perkantoran    33 non-null     int64
 13  Jembatan       33 non-null     int64
 14  Pabrik         33 non-null     int64
 15  Kios           33 non-null     int64
 16  Jenis Bencana  33 non-null     object
 17  Tahun          33 non-null     object
 18  id             33 non-null     int64
dtypes: int64(16), object(3)
memory usage: 6.2+ KB

In [19]:
df.index = pd.RangeIndex(len(df.index))

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Wilayah        33 non-null     object
 1   Jumlah         33 non-null     int64
 2   Meninggal      33 non-null     int64
 3   Hilang         33 non-null     int64
 4   Terluka        33 non-null     int64
 5   Menderita      33 non-null     int64
 6   Mengungsi      33 non-null     int64
 7   Rumah          33 non-null     int64
 8   Pendidikan     33 non-null     int64
 9   Kesehatan      33 non-null     int64
 10  Peribadatan    33 non-null     int64
 11  Fasum          33 non-null     int64
 12  Perkantoran    33 non-null     int64
 13  Jembatan       33 non-null     int64
 14  Pabrik         33 non-null     int64
 15  Kios           33 non-null     int64
 16  Jenis Bencana  33 non-null     object
 17  Tahun          33 non-null     object
 18  id             33 non-null     int64
dtypes: int64(16), object(3)
memory usage: 5.0+ KB

In [5]:
json_data_f=df_file.to_json(orient='records',indent=4)

In [6]:
json_data_f

'[\n    {\n        "Wilayah":"Aceh",\n        "Jumlah":56,\n        "Meninggal":0,\n        "Hilang":1,\n        "Terluka":0,\n        "Menderita":119127,\n        "Mengungsi":11232,\n        "Rumah":49,\n        "Pendidikan":1,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":4,\n        "Pabrik":0,\n        "Kios":10,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":5532831364498459970\n    },\n    {\n        "Wilayah":"Sumatera Utara",\n        "Jumlah":65,\n        "Meninggal":1,\n        "Hilang":0,\n        "Terluka":11,\n        "Menderita":102779,\n        "Mengungsi":1015,\n        "Rumah":10131,\n        "Pendidikan":11,\n        "Kesehatan":2,\n        "Peribadatan":2,\n        "Fasum":9,\n        "Perkantoran":3,\n        "Jembatan":6,\n        "Pabrik":1,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-7054326224685856717\n    },\n    {\n        "Wilayah":"Sumatera Barat",\n        "Jumlah":17,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":23830,\n        "Mengungsi":0,\n        "Rumah":10,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":3,\n        "Pabrik":0,\n        "Kios":7,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-3424620343974164553\n    },\n    {\n        "Wilayah":"Riau",\n        "Jumlah":14,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":11070,\n        "Mengungsi":600,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-4290370398864269807\n    },\n    {\n        "Wilayah":"Jambi",\n        "Jumlah":3,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":0,\n        "Mengungsi":0,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":4266915871318682695\n    },\n    {\n        "Wilayah":"Sumatera Selatan",\n        "Jumlah":21,\n        "Meninggal":2,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":5515,\n        "Mengungsi":105,\n        "Rumah":26,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-8239193690959760415\n    },\n    {\n        "Wilayah":"Bengkulu",\n        "Jumlah":9,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":2978,\n        "Mengungsi":0,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":1,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-7444047244058024512\n    },\n    {\n        "Wilayah":"Lampung",\n        "Jumlah":20,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":5437,\n        "Mengungsi":0,\n        "Rumah":1092,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":2,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-3241503174666867224\n    },\n    {\n        "Wilayah":"Bangka Belitung",\n        "Jumlah":75,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":2571,\n        "Mengungsi":1929,\n        "Rumah":1763,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":2,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-5198153680009679729\n    },\n    {\n        "Wilayah":"Kepulauan Riau",\n        "Jumlah":5,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":5707,\n        "Mengungsi":1540,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":2363648035627867923\n    },\n    {\n        "Wilayah":"DKI Jakarta",\n        "Jumlah":16,\n        "Meninggal":4,\n        "Hilang":1,\n        "Terluka":0,\n        "Menderita":30849,\n        "Mengungsi":7190,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":1350081022483842107\n    },\n    {\n        "Wilayah":"Jawa Barat",\n        "Jumlah":120,\n        "Meninggal":11,\n        "Hilang":0,\n        "Terluka":275,\n        "Menderita":989548,\n        "Mengungsi":97978,\n        "Rumah":438,\n        "Pendidikan":27,\n        "Kesehatan":5,\n        "Peribadatan":37,\n        "Fasum":0,\n        "Perkantoran":7,\n        "Jembatan":3,\n        "Pabrik":1,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":3906548518164760522\n    },\n    {\n        "Wilayah":"Jawa Tengah",\n        "Jumlah":276,\n        "Meninggal":91,\n        "Hilang":0,\n        "Terluka":2,\n        "Menderita":1021287,\n        "Mengungsi":11711,\n        "Rumah":1902,\n        "Pendidikan":6,\n        "Kesehatan":0,\n        "Peribadatan":14,\n        "Fasum":6,\n        "Perkantoran":4,\n        "Jembatan":158,\n        "Pabrik":0,\n        "Kios":2,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-238705540885376777\n    },\n    {\n        "Wilayah":"DI Yogyakarta",\n        "Jumlah":1,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":335,\n        "Mengungsi":0,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":1,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":8942684095506989572\n    },\n    {\n        "Wilayah":"Jawa Timur",\n        "Jumlah":125,\n        "Meninggal":2,\n        "Hilang":2,\n        "Terluka":0,\n        "Menderita":282542,\n        "Mengungsi":3552,\n        "Rumah":131,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":3,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":8237626711108532887\n    },\n    {\n        "Wilayah":"Banten",\n        "Jumlah":28,\n        "Meninggal":1,\n        "Hilang":0,\n        "Terluka":12,\n        "Menderita":60089,\n        "Mengungsi":7175,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":4850639628297375594\n    },\n    {\n        "Wilayah":"Bali",\n        "Jumlah":5,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":15,\n        "Mengungsi":0,\n        "Rumah":7,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":8172455212066817327\n    },\n    {\n        "Wilayah":"Nusa Tenggara Barat",\n        "Jumlah":46,\n        "Meninggal":7,\n        "Hilang":1,\n        "Terluka":0,\n        "Menderita":109430,\n        "Mengungsi":2410,\n        "Rumah":5784,\n        "Pendidikan":49,\n        "Kesehatan":29,\n        "Peribadatan":26,\n        "Fasum":0,\n        "Perkantoran":30,\n        "Jembatan":22,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":4666588397996357223\n    },\n    {\n        "Wilayah":"Nusa Tenggara Timur",\n        "Jumlah":33,\n        "Meninggal":239,\n        "Hilang":48,\n        "Terluka":218,\n        "Menderita":558482,\n        "Mengungsi":61092,\n        "Rumah":53845,\n        "Pendidikan":229,\n        "Kesehatan":98,\n        "Peribadatan":239,\n        "Fasum":14,\n        "Perkantoran":92,\n        "Jembatan":133,\n        "Pabrik":0,\n        "Kios":15,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-4442336844611965570\n    },\n    {\n        "Wilayah":"Kalimantan Barat",\n        "Jumlah":55,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":97850,\n        "Mengungsi":11879,\n        "Rumah":18,\n        "Pendidikan":1,\n        "Kesehatan":1,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":1,\n        "Jembatan":11,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-3478647132301299410\n    },\n    {\n        "Wilayah":"Kalimantan Tengah",\n        "Jumlah":20,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":47043,\n        "Mengungsi":0,\n        "Rumah":5,\n        "Pendidikan":1,\n        "Kesehatan":0,\n        "Peribadatan":1,\n        "Fasum":0,\n        "Perkantoran":1,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-8441593748352491094\n    },\n    {\n        "Wilayah":"Kalimantan Selatan",\n        "Jumlah":25,\n        "Meninggal":28,\n        "Hilang":0,\n        "Terluka":871,\n        "Menderita":648134,\n        "Mengungsi":177795,\n        "Rumah":21271,\n        "Pendidikan":586,\n        "Kesehatan":127,\n        "Peribadatan":497,\n        "Fasum":0,\n        "Perkantoran":197,\n        "Jembatan":38,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":9222327036058990205\n    },\n    {\n        "Wilayah":"Kalimantan Timur",\n        "Jumlah":8,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":17654,\n        "Mengungsi":65,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-8527688511520828755\n    },\n    {\n        "Wilayah":"Kalimantan Utara",\n        "Jumlah":8,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":27817,\n        "Mengungsi":0,\n        "Rumah":3,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":8124479838191493797\n    },\n    {\n        "Wilayah":"Sulawesi Utara",\n        "Jumlah":15,\n        "Meninggal":6,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":3506,\n        "Mengungsi":663,\n        "Rumah":3,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":233339165231530178\n    },\n    {\n        "Wilayah":"Sulawesi Tengah",\n        "Jumlah":60,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":2206,\n        "Mengungsi":958,\n        "Rumah":448,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":2,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":9,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-6124627827366007414\n    },\n    {\n        "Wilayah":"Sulawesi Selatan",\n        "Jumlah":15,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":28653,\n        "Mengungsi":7,\n        "Rumah":54,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":3,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-2865149246427024491\n    },\n    {\n        "Wilayah":"Sulawesi Tenggara",\n        "Jumlah":10,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":1805,\n        "Mengungsi":15,\n        "Rumah":36,\n        "Pendidikan":1,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":4,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":4409232549920256401\n    },\n    {\n        "Wilayah":"Gorontalo",\n        "Jumlah":6,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":5960,\n        "Mengungsi":185,\n        "Rumah":10,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":3,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":7832667091522636029\n    },\n    {\n        "Wilayah":"Sulawesi Barat",\n        "Jumlah":3,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":0,\n        "Mengungsi":358,\n        "Rumah":40,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":20,\n        "Perkantoran":0,\n        "Jembatan":2,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-2187193425455446095\n    },\n    {\n        "Wilayah":"Maluku",\n        "Jumlah":5,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":14481,\n        "Mengungsi":0,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":3008390533446843445\n    },\n    {\n        "Wilayah":"Maluku Utara",\n        "Jumlah":7,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":5992,\n        "Mengungsi":1801,\n        "Rumah":27,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":1,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-5933694593119513975\n    },\n    {\n        "Wilayah":"Papua",\n        "Jumlah":9,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":35,\n        "Menderita":41705,\n        "Mengungsi":5437,\n        "Rumah":1664,\n        "Pendidikan":1,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":16,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":956666211437697741\n    }\n]'

In [1]:
df_file

NameError: name 'df_file' is not defined

In [27]:
json_data_c=df_file.to_json('E:/tugas_koko/Mencari_Kerja/Kerjaan/Paw_Patrol/Development/Data/example_1.json',orient='columns',indent=4)

json_data_r=df_file.to_json(orient='records')
json_data_i=df_file.to_json(orient='index')
json_data_v=df_file.to_json(orient='values')
json_data_t=df_file.to_json(orient='table')
json_data=df_file.to_json()

In [23]:
json_data_c=df_file.to_json('E:/tugas_koko/Mencari_Kerja/Kerjaan/Paw_Patrol/Development/Data/example_1.json',orient='columns',indent=4)

In [24]:
json_data_s=df_file.to_json('E:/tugas_koko/Mencari_Kerja/Kerjaan/Paw_Patrol/Development/Data/example_1.json',indent=4)

In [19]:
filename = f"E:/tugas_koko/Mencari_Kerja/Kerjaan/Paw_Patrol/Development/Data/example.json"
with open(filename, 'w', encoding='utf-8') as f:
    json.dump(json_data_s, f, ensure_ascii=False)

In [28]:
json_data_c

In [29]:
print(json_data_c)

None

In [13]:
json_data_s

'{"columns":["Wilayah","Jumlah","Meninggal","Hilang","Terluka","Menderita","Mengungsi","Rumah","Pendidikan","Kesehatan","Peribadatan","Fasum","Perkantoran","Jembatan","Pabrik","Kios","Jenis Bencana","Tahun","id"],"index":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32],"data":[["Aceh",56,0,1,0,119127,11232,49,1,0,0,0,0,4,0,10,"Banjir","2021",7920538631479917782],["Sumatera Utara",65,1,0,11,102779,1015,10131,11,2,2,9,3,6,1,0,"Banjir","2021",-7507046870680908448],["Sumatera Barat",17,0,0,0,23830,0,10,0,0,0,0,0,3,0,7,"Banjir","2021",2319188487819841852],["Riau",14,0,0,0,11070,600,0,0,0,0,0,0,0,0,0,"Banjir","2021",4721149471773781077],["Jambi",3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Banjir","2021",3441652308983493490],["Sumatera Selatan",21,2,0,0,5515,105,26,0,0,0,0,0,0,0,0,"Banjir","2021",6108235340701542116],["Bengkulu",9,0,0,0,2978,0,0,0,0,0,0,0,1,0,0,"Banjir","2021",-3106392739219981891],["Lampung",20,0,0,0,5437,0,1092,0,0,0,0,0,2,0,0,"Banjir","2021",-7494394979291486326],["Bangka Belitung",75,0,0,0,2571,1929,1763,0,0,0,0,0,2,0,0,"Banjir","2021",7671591270451465370],["Kepulauan Riau",5,0,0,0,5707,1540,0,0,0,0,0,0,0,0,0,"Banjir","2021",4539684401216300777],["DKI Jakarta",16,4,1,0,30849,7190,0,0,0,0,0,0,0,0,0,"Banjir","2021",-939854812390080500],["Jawa Barat",120,11,0,275,989548,97978,438,27,5,37,0,7,3,1,0,"Banjir","2021",-2819973001627659778],["Jawa Tengah",276,91,0,2,1021287,11711,1902,6,0,14,6,4,158,0,2,"Banjir","2021",4583736285735495669],["DI Yogyakarta",1,0,0,0,335,0,0,0,0,0,0,0,1,0,0,"Banjir","2021",-7234925448876853399],["Jawa Timur",125,2,2,0,282542,3552,131,0,0,0,0,0,3,0,0,"Banjir","2021",-6974919019003870113],["Banten",28,1,0,12,60089,7175,0,0,0,0,0,0,0,0,0,"Banjir","2021",-5286602798215936374],["Bali",5,0,0,0,15,0,7,0,0,0,0,0,0,0,0,"Banjir","2021",-5494471108998620330],["Nusa Tenggara Barat",46,7,1,0,109430,2410,5784,49,29,26,0,30,22,0,0,"Banjir","2021",4681036591055429374],["Nusa Tenggara Timur",33,239,48,218,558482,61092,53845,229,98,239,14,92,133,0,15,"Banjir","2021",-3338647887300975313],["Kalimantan Barat",55,0,0,0,97850,11879,18,1,1,0,0,1,11,0,0,"Banjir","2021",-5469487247126876577],["Kalimantan Tengah",20,0,0,0,47043,0,5,1,0,1,0,1,0,0,0,"Banjir","2021",3660203498773851332],["Kalimantan Selatan",25,28,0,871,648134,177795,21271,586,127,497,0,197,38,0,0,"Banjir","2021",5961015855813289290],["Kalimantan Timur",8,0,0,0,17654,65,0,0,0,0,0,0,0,0,0,"Banjir","2021",2309016456172211510],["Kalimantan Utara",8,0,0,0,27817,0,3,0,0,0,0,0,0,0,0,"Banjir","2021",-1124502605637985532],["Sulawesi Utara",15,6,0,0,3506,663,3,0,0,0,0,0,0,0,0,"Banjir","2021",-8560318930587824630],["Sulawesi Tengah",60,0,0,0,2206,958,448,0,0,2,0,0,9,0,0,"Banjir","2021",-3139853741366295314],["Sulawesi Selatan",15,0,0,0,28653,7,54,0,0,0,0,0,3,0,0,"Banjir","2021",-5808755525697514012],["Sulawesi Tenggara",10,0,0,0,1805,15,36,1,0,0,0,0,4,0,0,"Banjir","2021",5381434641678006778],["Gorontalo",6,0,0,0,5960,185,10,0,0,0,0,0,3,0,0,"Banjir","2021",-454651211945689544],["Sulawesi Barat",3,0,0,0,0,358,40,0,0,0,20,0,2,0,0,"Banjir","2021",-6231100096931700630],["Maluku",5,0,0,0,14481,0,0,0,0,0,0,0,0,0,0,"Banjir","2021",6908975212369032664],["Maluku Utara",7,0,0,0,5992,1801,27,0,0,0,0,0,1,0,0,"Banjir","2021",-2720388674585896265],["Papua",9,0,0,35,41705,5437,1664,1,0,0,0,0,16,0,0,"Banjir","2021",-3202343595958023966]]}'

In [14]:
json_data_r

'[{"Wilayah":"Aceh","Jumlah":56,"Meninggal":0,"Hilang":1,"Terluka":0,"Menderita":119127,"Mengungsi":11232,"Rumah":49,"Pendidikan":1,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":4,"Pabrik":0,"Kios":10,"Jenis Bencana":"Banjir","Tahun":"2021","id":7920538631479917782},{"Wilayah":"Sumatera Utara","Jumlah":65,"Meninggal":1,"Hilang":0,"Terluka":11,"Menderita":102779,"Mengungsi":1015,"Rumah":10131,"Pendidikan":11,"Kesehatan":2,"Peribadatan":2,"Fasum":9,"Perkantoran":3,"Jembatan":6,"Pabrik":1,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-7507046870680908448},{"Wilayah":"Sumatera Barat","Jumlah":17,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":23830,"Mengungsi":0,"Rumah":10,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":3,"Pabrik":0,"Kios":7,"Jenis Bencana":"Banjir","Tahun":"2021","id":2319188487819841852},{"Wilayah":"Riau","Jumlah":14,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":11070,"Mengungsi":600,"Rumah":0,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":4721149471773781077},{"Wilayah":"Jambi","Jumlah":3,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":0,"Mengungsi":0,"Rumah":0,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":3441652308983493490},{"Wilayah":"Sumatera Selatan","Jumlah":21,"Meninggal":2,"Hilang":0,"Terluka":0,"Menderita":5515,"Mengungsi":105,"Rumah":26,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":6108235340701542116},{"Wilayah":"Bengkulu","Jumlah":9,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":2978,"Mengungsi":0,"Rumah":0,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":1,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-3106392739219981891},{"Wilayah":"Lampung","Jumlah":20,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":5437,"Mengungsi":0,"Rumah":1092,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":2,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-7494394979291486326},{"Wilayah":"Bangka Belitung","Jumlah":75,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":2571,"Mengungsi":1929,"Rumah":1763,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":2,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":7671591270451465370},{"Wilayah":"Kepulauan Riau","Jumlah":5,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":5707,"Mengungsi":1540,"Rumah":0,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":4539684401216300777},{"Wilayah":"DKI Jakarta","Jumlah":16,"Meninggal":4,"Hilang":1,"Terluka":0,"Menderita":30849,"Mengungsi":7190,"Rumah":0,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-939854812390080500},{"Wilayah":"Jawa Barat","Jumlah":120,"Meninggal":11,"Hilang":0,"Terluka":275,"Menderita":989548,"Mengungsi":97978,"Rumah":438,"Pendidikan":27,"Kesehatan":5,"Peribadatan":37,"Fasum":0,"Perkantoran":7,"Jembatan":3,"Pabrik":1,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-2819973001627659778},{"Wilayah":"Jawa Tengah","Jumlah":276,"Meninggal":91,"Hilang":0,"Terluka":2,"Menderita":1021287,"Mengungsi":11711,"Rumah":1902,"Pendidikan":6,"Kesehatan":0,"Peribadatan":14,"Fasum":6,"Perkantoran":4,"Jembatan":158,"Pabrik":0,"Kios":2,"Jenis Bencana":"Banjir","Tahun":"2021","id":4583736285735495669},{"Wilayah":"DI Yogyakarta","Jumlah":1,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":335,"Mengungsi":0,"Rumah":0,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":1,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-7234925448876853399},{"Wilayah":"Jawa Timur","Jumlah":125,"Meninggal":2,"Hilang":2,"Terluka":0,"Menderita":282542,"Mengungsi":3552,"Rumah":131,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":3,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-6974919019003870113},{"Wilayah":"Banten","Jumlah":28,"Meninggal":1,"Hilang":0,"Terluka":12,"Menderita":60089,"Mengungsi":7175,"Rumah":0,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-5286602798215936374},{"Wilayah":"Bali","Jumlah":5,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":15,"Mengungsi":0,"Rumah":7,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-5494471108998620330},{"Wilayah":"Nusa Tenggara Barat","Jumlah":46,"Meninggal":7,"Hilang":1,"Terluka":0,"Menderita":109430,"Mengungsi":2410,"Rumah":5784,"Pendidikan":49,"Kesehatan":29,"Peribadatan":26,"Fasum":0,"Perkantoran":30,"Jembatan":22,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":4681036591055429374},{"Wilayah":"Nusa Tenggara Timur","Jumlah":33,"Meninggal":239,"Hilang":48,"Terluka":218,"Menderita":558482,"Mengungsi":61092,"Rumah":53845,"Pendidikan":229,"Kesehatan":98,"Peribadatan":239,"Fasum":14,"Perkantoran":92,"Jembatan":133,"Pabrik":0,"Kios":15,"Jenis Bencana":"Banjir","Tahun":"2021","id":-3338647887300975313},{"Wilayah":"Kalimantan Barat","Jumlah":55,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":97850,"Mengungsi":11879,"Rumah":18,"Pendidikan":1,"Kesehatan":1,"Peribadatan":0,"Fasum":0,"Perkantoran":1,"Jembatan":11,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-5469487247126876577},{"Wilayah":"Kalimantan Tengah","Jumlah":20,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":47043,"Mengungsi":0,"Rumah":5,"Pendidikan":1,"Kesehatan":0,"Peribadatan":1,"Fasum":0,"Perkantoran":1,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":3660203498773851332},{"Wilayah":"Kalimantan Selatan","Jumlah":25,"Meninggal":28,"Hilang":0,"Terluka":871,"Menderita":648134,"Mengungsi":177795,"Rumah":21271,"Pendidikan":586,"Kesehatan":127,"Peribadatan":497,"Fasum":0,"Perkantoran":197,"Jembatan":38,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":5961015855813289290},{"Wilayah":"Kalimantan Timur","Jumlah":8,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":17654,"Mengungsi":65,"Rumah":0,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":2309016456172211510},{"Wilayah":"Kalimantan Utara","Jumlah":8,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":27817,"Mengungsi":0,"Rumah":3,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-1124502605637985532},{"Wilayah":"Sulawesi Utara","Jumlah":15,"Meninggal":6,"Hilang":0,"Terluka":0,"Menderita":3506,"Mengungsi":663,"Rumah":3,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-8560318930587824630},{"Wilayah":"Sulawesi Tengah","Jumlah":60,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":2206,"Mengungsi":958,"Rumah":448,"Pendidikan":0,"Kesehatan":0,"Peribadatan":2,"Fasum":0,"Perkantoran":0,"Jembatan":9,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-3139853741366295314},{"Wilayah":"Sulawesi Selatan","Jumlah":15,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":28653,"Mengungsi":7,"Rumah":54,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":3,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-5808755525697514012},{"Wilayah":"Sulawesi Tenggara","Jumlah":10,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":1805,"Mengungsi":15,"Rumah":36,"Pendidikan":1,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":4,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":5381434641678006778},{"Wilayah":"Gorontalo","Jumlah":6,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":5960,"Mengungsi":185,"Rumah":10,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":3,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-454651211945689544},{"Wilayah":"Sulawesi Barat","Jumlah":3,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":0,"Mengungsi":358,"Rumah":40,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":20,"Perkantoran":0,"Jembatan":2,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-6231100096931700630},{"Wilayah":"Maluku","Jumlah":5,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":14481,"Mengungsi":0,"Rumah":0,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":0,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":6908975212369032664},{"Wilayah":"Maluku Utara","Jumlah":7,"Meninggal":0,"Hilang":0,"Terluka":0,"Menderita":5992,"Mengungsi":1801,"Rumah":27,"Pendidikan":0,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":1,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-2720388674585896265},{"Wilayah":"Papua","Jumlah":9,"Meninggal":0,"Hilang":0,"Terluka":35,"Menderita":41705,"Mengungsi":5437,"Rumah":1664,"Pendidikan":1,"Kesehatan":0,"Peribadatan":0,"Fasum":0,"Perkantoran":0,"Jembatan":16,"Pabrik":0,"Kios":0,"Jenis Bencana":"Banjir","Tahun":"2021","id":-3202343595958023966}]'

In [10]:
json_data_i

'{\n    "0":{\n        "Wilayah":"Aceh",\n        "Jumlah":56,\n        "Meninggal":0,\n        "Hilang":1,\n        "Terluka":0,\n        "Menderita":119127,\n        "Mengungsi":11232,\n        "Rumah":49,\n        "Pendidikan":1,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":4,\n        "Pabrik":0,\n        "Kios":10,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":7920538631479917782\n    },\n    "1":{\n        "Wilayah":"Sumatera Utara",\n        "Jumlah":65,\n        "Meninggal":1,\n        "Hilang":0,\n        "Terluka":11,\n        "Menderita":102779,\n        "Mengungsi":1015,\n        "Rumah":10131,\n        "Pendidikan":11,\n        "Kesehatan":2,\n        "Peribadatan":2,\n        "Fasum":9,\n        "Perkantoran":3,\n        "Jembatan":6,\n        "Pabrik":1,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-7507046870680908448\n    },\n    "2":{\n        "Wilayah":"Sumatera Barat",\n        "Jumlah":17,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":23830,\n        "Mengungsi":0,\n        "Rumah":10,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":3,\n        "Pabrik":0,\n        "Kios":7,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":2319188487819841852\n    },\n    "3":{\n        "Wilayah":"Riau",\n        "Jumlah":14,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":11070,\n        "Mengungsi":600,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":4721149471773781077\n    },\n    "4":{\n        "Wilayah":"Jambi",\n        "Jumlah":3,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":0,\n        "Mengungsi":0,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":3441652308983493490\n    },\n    "5":{\n        "Wilayah":"Sumatera Selatan",\n        "Jumlah":21,\n        "Meninggal":2,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":5515,\n        "Mengungsi":105,\n        "Rumah":26,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":6108235340701542116\n    },\n    "6":{\n        "Wilayah":"Bengkulu",\n        "Jumlah":9,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":2978,\n        "Mengungsi":0,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":1,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-3106392739219981891\n    },\n    "7":{\n        "Wilayah":"Lampung",\n        "Jumlah":20,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":5437,\n        "Mengungsi":0,\n        "Rumah":1092,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":2,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-7494394979291486326\n    },\n    "8":{\n        "Wilayah":"Bangka Belitung",\n        "Jumlah":75,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":2571,\n        "Mengungsi":1929,\n        "Rumah":1763,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":2,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":7671591270451465370\n    },\n    "9":{\n        "Wilayah":"Kepulauan Riau",\n        "Jumlah":5,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":5707,\n        "Mengungsi":1540,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":4539684401216300777\n    },\n    "10":{\n        "Wilayah":"DKI Jakarta",\n        "Jumlah":16,\n        "Meninggal":4,\n        "Hilang":1,\n        "Terluka":0,\n        "Menderita":30849,\n        "Mengungsi":7190,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-939854812390080500\n    },\n    "11":{\n        "Wilayah":"Jawa Barat",\n        "Jumlah":120,\n        "Meninggal":11,\n        "Hilang":0,\n        "Terluka":275,\n        "Menderita":989548,\n        "Mengungsi":97978,\n        "Rumah":438,\n        "Pendidikan":27,\n        "Kesehatan":5,\n        "Peribadatan":37,\n        "Fasum":0,\n        "Perkantoran":7,\n        "Jembatan":3,\n        "Pabrik":1,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-2819973001627659778\n    },\n    "12":{\n        "Wilayah":"Jawa Tengah",\n        "Jumlah":276,\n        "Meninggal":91,\n        "Hilang":0,\n        "Terluka":2,\n        "Menderita":1021287,\n        "Mengungsi":11711,\n        "Rumah":1902,\n        "Pendidikan":6,\n        "Kesehatan":0,\n        "Peribadatan":14,\n        "Fasum":6,\n        "Perkantoran":4,\n        "Jembatan":158,\n        "Pabrik":0,\n        "Kios":2,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":4583736285735495669\n    },\n    "13":{\n        "Wilayah":"DI Yogyakarta",\n        "Jumlah":1,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":335,\n        "Mengungsi":0,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":1,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-7234925448876853399\n    },\n    "14":{\n        "Wilayah":"Jawa Timur",\n        "Jumlah":125,\n        "Meninggal":2,\n        "Hilang":2,\n        "Terluka":0,\n        "Menderita":282542,\n        "Mengungsi":3552,\n        "Rumah":131,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":3,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-6974919019003870113\n    },\n    "15":{\n        "Wilayah":"Banten",\n        "Jumlah":28,\n        "Meninggal":1,\n        "Hilang":0,\n        "Terluka":12,\n        "Menderita":60089,\n        "Mengungsi":7175,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-5286602798215936374\n    },\n    "16":{\n        "Wilayah":"Bali",\n        "Jumlah":5,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":15,\n        "Mengungsi":0,\n        "Rumah":7,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-5494471108998620330\n    },\n    "17":{\n        "Wilayah":"Nusa Tenggara Barat",\n        "Jumlah":46,\n        "Meninggal":7,\n        "Hilang":1,\n        "Terluka":0,\n        "Menderita":109430,\n        "Mengungsi":2410,\n        "Rumah":5784,\n        "Pendidikan":49,\n        "Kesehatan":29,\n        "Peribadatan":26,\n        "Fasum":0,\n        "Perkantoran":30,\n        "Jembatan":22,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":4681036591055429374\n    },\n    "18":{\n        "Wilayah":"Nusa Tenggara Timur",\n        "Jumlah":33,\n        "Meninggal":239,\n        "Hilang":48,\n        "Terluka":218,\n        "Menderita":558482,\n        "Mengungsi":61092,\n        "Rumah":53845,\n        "Pendidikan":229,\n        "Kesehatan":98,\n        "Peribadatan":239,\n        "Fasum":14,\n        "Perkantoran":92,\n        "Jembatan":133,\n        "Pabrik":0,\n        "Kios":15,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-3338647887300975313\n    },\n    "19":{\n        "Wilayah":"Kalimantan Barat",\n        "Jumlah":55,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":97850,\n        "Mengungsi":11879,\n        "Rumah":18,\n        "Pendidikan":1,\n        "Kesehatan":1,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":1,\n        "Jembatan":11,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-5469487247126876577\n    },\n    "20":{\n        "Wilayah":"Kalimantan Tengah",\n        "Jumlah":20,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":47043,\n        "Mengungsi":0,\n        "Rumah":5,\n        "Pendidikan":1,\n        "Kesehatan":0,\n        "Peribadatan":1,\n        "Fasum":0,\n        "Perkantoran":1,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":3660203498773851332\n    },\n    "21":{\n        "Wilayah":"Kalimantan Selatan",\n        "Jumlah":25,\n        "Meninggal":28,\n        "Hilang":0,\n        "Terluka":871,\n        "Menderita":648134,\n        "Mengungsi":177795,\n        "Rumah":21271,\n        "Pendidikan":586,\n        "Kesehatan":127,\n        "Peribadatan":497,\n        "Fasum":0,\n        "Perkantoran":197,\n        "Jembatan":38,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":5961015855813289290\n    },\n    "22":{\n        "Wilayah":"Kalimantan Timur",\n        "Jumlah":8,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":17654,\n        "Mengungsi":65,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":2309016456172211510\n    },\n    "23":{\n        "Wilayah":"Kalimantan Utara",\n        "Jumlah":8,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":27817,\n        "Mengungsi":0,\n        "Rumah":3,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-1124502605637985532\n    },\n    "24":{\n        "Wilayah":"Sulawesi Utara",\n        "Jumlah":15,\n        "Meninggal":6,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":3506,\n        "Mengungsi":663,\n        "Rumah":3,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-8560318930587824630\n    },\n    "25":{\n        "Wilayah":"Sulawesi Tengah",\n        "Jumlah":60,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":2206,\n        "Mengungsi":958,\n        "Rumah":448,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":2,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":9,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-3139853741366295314\n    },\n    "26":{\n        "Wilayah":"Sulawesi Selatan",\n        "Jumlah":15,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":28653,\n        "Mengungsi":7,\n        "Rumah":54,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":3,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-5808755525697514012\n    },\n    "27":{\n        "Wilayah":"Sulawesi Tenggara",\n        "Jumlah":10,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":1805,\n        "Mengungsi":15,\n        "Rumah":36,\n        "Pendidikan":1,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":4,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":5381434641678006778\n    },\n    "28":{\n        "Wilayah":"Gorontalo",\n        "Jumlah":6,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":5960,\n        "Mengungsi":185,\n        "Rumah":10,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":3,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-454651211945689544\n    },\n    "29":{\n        "Wilayah":"Sulawesi Barat",\n        "Jumlah":3,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":0,\n        "Mengungsi":358,\n        "Rumah":40,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":20,\n        "Perkantoran":0,\n        "Jembatan":2,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-6231100096931700630\n    },\n    "30":{\n        "Wilayah":"Maluku",\n        "Jumlah":5,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":14481,\n        "Mengungsi":0,\n        "Rumah":0,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":0,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":6908975212369032664\n    },\n    "31":{\n        "Wilayah":"Maluku Utara",\n        "Jumlah":7,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":0,\n        "Menderita":5992,\n        "Mengungsi":1801,\n        "Rumah":27,\n        "Pendidikan":0,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":1,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-2720388674585896265\n    },\n    "32":{\n        "Wilayah":"Papua",\n        "Jumlah":9,\n        "Meninggal":0,\n        "Hilang":0,\n        "Terluka":35,\n        "Menderita":41705,\n        "Mengungsi":5437,\n        "Rumah":1664,\n        "Pendidikan":1,\n        "Kesehatan":0,\n        "Peribadatan":0,\n        "Fasum":0,\n        "Perkantoran":0,\n        "Jembatan":16,\n        "Pabrik":0,\n        "Kios":0,\n        "Jenis Bencana":"Banjir",\n        "Tahun":"2021",\n        "id":-3202343595958023966\n    }\n}'

In [8]:
file_name = os.path.splitext(os.path.basename(path_file))[0]
    # Extract the year from the file name
year = file_name.split('_')[1]
disaster = file_name.split('_')[0]

In [17]:
import json

In [12]:
filename = f"E:/tugas_koko/Mencari_Kerja/Kerjaan/Paw_Patrol/Development/Data/{disaster}_{year}.json"
    # with open(filename, 'w', indent=4) as f:
    #     json.dump(json_data, f)
with open(filename, 'w', encoding='utf-8') as f:
    # json.dump(json_data, f, ensure_ascii=False, indent=4)
    f.write(json.dumps(json_data,ensure_ascii=False,indent=4))

In [2]:
import numpy as np
import pandas as pd

In [7]:
data = np.array([['1', '2'], ['3', '4']])
  
dataFrame = pd.DataFrame(data, columns = ['col1', 'col2'])
json = dataFrame.to_json()

In [8]:
json

'{"col1":{"0":"1","1":"3"},"col2":{"0":"2","1":"4"}}'